version: '3'
services:
  std01-node-server: 
    container_name: std01-node-server
    build: .      # ตำแหน่ง dockerfile   
    ports:
      - "8000:8000"
  db:
    image: mysql:latest
    container_name: std01-mysql
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD : root
      MYSQL_DATABASE: std01
    ports:
      - "3307:3306"
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: std01-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db  

